apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Values.ArgoCDAppName | quote }}
    git-revision: {{ .Values.gitRevision | quote }}
  name: demoapps.demo.mycompany.com
spec:
  group: demo.mycompany.com
  names:
    kind: DemoApp
    plural: demoapps
    singular: demoapp
    shortNames:
      - dapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
