---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-sa
  namespace: acs-setup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-deleter
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-deleter-binding
subjects:
  - name: delete-sa
    kind: ServiceAccount
    namespace: acs-setup
roleRef:
  kind: ClusterRole
  name: crd-deleter
  apiGroup: rbac.authorization.k8s.io