apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgetns.example.com
  annotations:
    argocd.argoproj.io/tracking-id: crd-app:argocd:CustomResourceDefinition:widgetns.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
  scope: Namespaced
  names:
    plural: widgetns
    singular: widgetn
    kind: Widgetn
    shortNames:
    - wdn

