apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  argocd.argoproj.io/tracking-id: demoapp-one:apiextensions.k8s.io/CustomResourceDefinition:widgets.example.com
  name: widgets.example.com
  labels:
    app.kubernetes.io/instance: demoapp-one
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
  scope: Namespaced
  names:
    plural: widgets
    singular: widget
    kind: Widget
    shortNames:
    - wd

